name: thesis_generator
description: "thesis generator"
publish_to: 'none'
version: 12.0.0+12

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cloud_firestore: ^5.6.9
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_quill: ^11.4.1
  pdf: ^3.10.7
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  js: ^0.6.7
  firebase_core: ^3.14.0
  firebase_core_web: ^2.10.0
  permission_handler: ^11.0.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.2
  universal_html: ^2.2.3
  google_mobile_ads: ^5.2.0
  country_flags: ^2.2.0
  translator: ^1.0.0
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^28.1.37
  share_plus: ^7.1.0
  printing: ^5.11.0
  in_app_review: ^2.0.8
  facebook_audience_network: ^1.0.1
  flutter_rating_bar: ^4.0.1
  onesignal_flutter: ^5.0.4
  flutter_carousel_widget: ^2.1.2
  in_app_purchase: ^3.2.1
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^1.0.0
  media_store_plus: ^0.1.3
  app_tracking_transparency: ^2.0.6+1
  firebase_analytics: ^11.3.0
  file_picker: ^8.1.6
  appsflyer_sdk: ^6.12.2
  firebase_remote_config: ^5.1.0
  superwallkit_flutter: ^2.0.8
  cached_network_image: ^3.4.1
  video_player: ^2.9.5
  webview_flutter_wkwebview: ^3.18.5
  google_sign_in: ^6.1.6
  firebase_auth: ^5.3.0
  http: ^1.4.0
  stripe_js: ^2.0.0 
  cloud_functions: ^5.1.0
  phosphor_flutter: ^2.1.0 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
